[stream_processors]
  [stream_processors."zstd"]
    accepts = ["application/vnd.oci.image.layer.v1.tar+zstd"]
    returns = "application/vnd.oci.image.layer.v1.tar+zstd"
    path = "zstd"
    args = ["-dcf"]
